name: Deploy to Hostinger
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Hostinger
      run: |
        sudo apt-get update
        sudo apt-get -y install lftp
        lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; set ssl:verify-certificate no; mirror -Rnev ./ ./public_html/capisen"
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }} 
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }} 
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} 
